name: Tokens

on:
  pull_request:
    branches: 
      - main
    paths: 
      - 'packages/tokens/src/figma/**'

permissions: 
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn workspace @slds/tokens build
      - name: Commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Generate token assets
          CI_COMMIT_AUTHOR: CI
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push      
