name: Tokens

on:
  push:
    branches-ignore: 
      - main
    paths: 
      - 'packages/tokens/src/figma/**'

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn workspace @slds/tokens build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '⚙️ Generate theme tokens'
