name: Tokens

on:
  pull_request:
    branches: 
      - main
    paths: 
      - 'packages/tokens/src/figma/**'

permissions: 
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn workspace @slds/tokens build
      - id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Commit and push generated token assets
        if: steps.changes.outputs.changed == 1
        env: 
          CI_COMMIT_MESSAGE: Generate token assets
          CI_COMMIT_AUTHOR: CI
        run: |
          git config user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config user.email "username@users.noreply.github.com"
          git add .
          git status
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push      
